CREATE DATABASE QLSP
--
CREATE TABLE HANG
(
	MaSoHang	VARCHAR(10) NOT NULL
	CONSTRAINT PK_HANG_MaSoHang	PRIMARY KEY(MaSoHang),
	TenHang	VARCHAR(20) ,
	DiaChi	VARCHAR(30),
	DienThoai	INT
)
CREATE TABLE SANPHAM
(
	MaSanPham	VARCHAR(30) NOT NULL
	CONSTRAINT PK_SANPHAM_MaSanPham PRIMARY KEY(MaSanPham),
	TenSanPham	NVARCHAR(50) ,
	MaSoHang	VARCHAR(10),
	Gia	INT,
	SoLuong INT ,
	DonVi	VARCHAR(30),
	MoTa	NVARCHAR(40)
	CONSTRAINT FK_HANG_SANPHAM FOREIGN KEY (MaSoHang) REFERENCES HANG(MaSoHang)
)
--Tao Bang
--Bang hang
	INSERT INTO HANG VALUES('123','ASUS','USA',983232)
	INSERT INTO HANG VALUES('124','Dell','USA',974392)
	INSERT INTO HANG VALUES('125','MSI','USA',737593)
	INSERT INTO HANG VALUES('126','Macbook','USA',478432)
	INSERT INTO HANG VALUES('127','Acer','USA',495974)
	INSERT INTO HANG VALUES('128','Nokia','"Finland',974859)
	INSERT INTO HANG VALUES('129','IPhone','USA',73453)
	INSERT INTO HANG VALUES('122','SamSung','Korea',0253972)
	INSERT INTO HANG VALUES('121','Lenovo','USA',759722)
--Bang sanPham
	INSERT INTO SANPHAM VALUES('SP01',N'Máy Tính T450','123',1000,10,'Chiec',N'Máy nhập cũ')
	INSERT INTO SANPHAM VALUES('SP02',N'Điện thoại Nokia 5670','128',200,200,'Chiec',N'Điện Thoại Đang Hot')
	INSERT INTO SANPHAM VALUES('SP03',N'Máy In SamSung 450','122',100,10,'Chiec',N'Máy in đang loại bình')
	--
	--4
	--4.a
	SELECT MaSoHang,TenHang
	FROM HANG
	--4.b
	SELECT MaSanPham,TenSanPham
	FROM SANPHAM
	--5
	--5.a
	SELECT TenHang FROM HANG
	ORDER BY TenHang desc
	--5.b
	SELECT MaSanPham,TenSanPham,SoLuong FROM SANPHAM
	ORDER BY SoLuong DESC
	--5.c
	SELECT * FROM HANG
	WHERE TenHang='ASUS'
	--5.d
	SELECT TenSanPham,MaSanPham,SoLuong
	FROM SANPHAM
	WHERE SoLuong<11
	--5e
	SELECT MaSanPham,TenSanPham,MaSoHang
	 FROM SanPham
	WHERE MaSoHang ='123' 
	--6
	--6a
	SELECT COUNT(MaSoHang) AS 'Tong So Hang'
	FROM HANG
	--6b
	SELECT COUNT(MaSanPham) AS 'Tong So San Pham'
	FROM SANPHAM
	--6c
	SELECT COUNT(MaSanPham) As'Tong So'
	FROM SANPHAM,HANG
	WHERE TenHang='ASUS'
	--6d
	SELECT SUM(SoLuong) AS 'Tong SO'
	FROM SANPHAM
	--7
	--7a
	--7b
	Update HANG
     Set DienThoai = ''
	WHERE DienThoai LIKE '0%'

	--8
	--8a
	CREATE UNIQUE INDEX INDEX_Tenhang
     ON HANG(TenHang);
	 --
	 CREATE UNIQUE INDEX INDEX_MoTa
	 ON SANPHAM(MoTa)
	 --8b
	 CREATE VIEW VIEW_SANPHAM AS
	 SELECT MaSanPham,TenSanPham,Gia
	 FROM SANPHAM
	 SELECT * FROM  VIEW_SANPHAM
	 --
	 CREATE VIEW VIEW_SANPHAM_HANG AS
	 SELECT MaSanPham,TenSanPham,TenHang
	 FROM SANPHAM,HANG
	 SELECT * FROM VIEW_SANPHAM_HANG
